GET http://localhost:5000/api/users/2

###

GET http://localhost:5000/api/users

###

GET http://localhost:5000/library

###

GET http://localhost:5000/library?tags=thriller

###

GET http://localhost:5000/library/67

###